apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: shporaai
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://shporaai-postgres:5432/shporaai_db"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  JWT_SECRET: "DEV-JWT-SECRET"
  JWT_ACCESS_EXPIRATION: "1800000"
  JWT_REFRESH_EXPIRATION: "1209600000"