apiVersion: v1
kind: Secret
metadata:
  name: shporaai-postgres-secret
  namespace: shporaai
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  POSTGRES_DB: shporaai_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres