apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: shporaai
type: Opaque
stringData:
  mail-host: "smtp.gmail.com"
  mail-port: "587"
  mail-username: "your-gmail@gmail.com"
  mail-password: "YOUR-APP-PASSWORD"