apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress
  - postgres
  - redis
  - kafka
  - user-service
  - notification-service
  - ai-service
  - frontend